version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: training_diary_db
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_psw
      - POSTGRES_DB=training-diary
    ports:
      - "5435:5432"
    networks:
      - vm_net

  # Prometheus container
  prometheus:
    image: prom/prometheus:v2.29.2
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - vm_net
    restart: always

  # VictoriaMetrics instance
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.101.0
    ports:
      - "8428:8428"
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    networks:
      - vm_net
    restart: always

  # Grafana instance
  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafanadata:/var/lib/grafana
    networks:
      - vm_net
    restart: always

volumes:
  vmdata: {}
  grafanadata: {}

networks:
  vm_net: