version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: training_diary_db
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_psw
      - POSTGRES_DB=training-diary
    ports:
      - "5435:5432"