spring:
  port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5435/training-diary
    username: postgres_user
    password: postgres_psw
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db.changelog/changelog.xml
    liquibase-schema: migration

  jwt:
    secret: c3VwZXJwdXBlcmR1cGVybWVnYWhhcmfwef43gt543r445hg43frerh4y56efreRvdmVydG9waGlnaHNlY3JldA==
    access: 3600000
    refresh: 2592000000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: training-diary
audit:
  aspect:
    enabled: true
