spring:
  port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5435/training-diary
    username: postgres_user
    password: postgres_psw
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db.changelog/changelog.xml
    liquibase-schema: migration

  jwt:
    secret: c3VwZXJwdXBlcmR1cGVybWVnYWhhcmfwef43gt543r445hg43frerh4y56efreRvdmVydG9waGlnaHNlY3JldA==
    access: 3600000
    refresh: 2592000000

audit:
  aspect:
    enabled: true
