global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'training-diary'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']